"""create configurations table

Revision ID: 0539ee7a63ea
Revises: 69797e504058
Create Date: 2026-09-12 10:33:24.642955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0539ee7a63ea'
down_revision: Union[str, Sequence[str], None] = '69797e504058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upload_status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_created_at'), 'configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_configurations_uploaded_by'), 'configurations', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_uploaded_by'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_created_at'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
