"""create learned mappings table

Revision ID: 47a317493fca
Revises: cdbf0eaec434
Create Date: 2026-09-12 21:55:58.557982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a317493fca'
down_revision: Union[str, Sequence[str], None] = 'cdbf0eaec434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configuration_pattern', sa.Text(), nullable=False),
    sa.Column('security_category', sa.String(length=100), nullable=False),
    sa.Column('baseline_parameter', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_mappings_created_at'), 'learned_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_learned_mappings_created_by'), 'learned_mappings', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learned_mappings_created_by'), table_name='learned_mappings')
    op.drop_index(op.f('ix_learned_mappings_created_at'), table_name='learned_mappings')
    op.drop_table('learned_mappings')
    # ### end Alembic commands ###
