"""create analysis runs table

Revision ID: 5dac540be721
Revises: 2ba577f559c0
Create Date: 2026-09-19 17:49:21.478483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dac540be721'
down_revision: Union[str, Sequence[str], None] = '2ba577f559c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('selected_frameworks', sa.JSON(), nullable=False),
    sa.Column('device_intelligence', sa.JSON(), nullable=False),
    sa.Column('parser', sa.JSON(), nullable=False),
    sa.Column('security_baseline', sa.JSON(), nullable=False),
    sa.Column('compliance', sa.JSON(), nullable=False),
    sa.Column('framework_results', sa.JSON(), nullable=False),
    sa.Column('ai_ingestion', sa.JSON(), nullable=False),
    sa.Column('unknown_lines', sa.JSON(), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_analyzed_by'), 'analysis_runs', ['analyzed_by'], unique=False)
    op.create_index(op.f('ix_analysis_runs_configuration_id'), 'analysis_runs', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_configuration_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_analyzed_by'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
