"""create bulk analysis jobs table

Revision ID: acfb1816f927
Revises: 47a317493fca
Create Date: 2026-09-13 15:27:38.227906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfb1816f927'
down_revision: Union[str, Sequence[str], None] = '47a317493fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_configurations', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('selected_frameworks', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_analysis_jobs_created_at'), 'bulk_analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_analysis_jobs_created_by'), 'bulk_analysis_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_bulk_analysis_jobs_status'), 'bulk_analysis_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_analysis_jobs_status'), table_name='bulk_analysis_jobs')
    op.drop_index(op.f('ix_bulk_analysis_jobs_created_by'), table_name='bulk_analysis_jobs')
    op.drop_index(op.f('ix_bulk_analysis_jobs_created_at'), table_name='bulk_analysis_jobs')
    op.drop_table('bulk_analysis_jobs')
    # ### end Alembic commands ###
