"""create remediation requests table

Revision ID: e658b61634a3
Revises: acfb1816f927
Create Date: 2026-09-14 01:14:44.651956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e658b61634a3'
down_revision: Union[str, Sequence[str], None] = 'acfb1816f927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('control', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('verification_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_requests_configuration_id'), 'remediation_requests', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_remediation_requests_created_at'), 'remediation_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_remediation_requests_device_id'), 'remediation_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_remediation_requests_requested_by'), 'remediation_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_remediation_requests_rule_id'), 'remediation_requests', ['rule_id'], unique=False)
    op.create_index(op.f('ix_remediation_requests_state'), 'remediation_requests', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_requests_state'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_rule_id'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_requested_by'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_device_id'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_created_at'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_configuration_id'), table_name='remediation_requests')
    op.drop_table('remediation_requests')
    # ### end Alembic commands ###
